exclude: '.*test.*'
repos:
-   repo: https://github.com/Intsights/flake8-intsights
    rev: v0.1.5
    hooks:
    -   id: flake8-intsights
-   repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    -   id: mypy
