---
exclude: '.*(test|benchmark).*'
repos:
  - repo: https://github.com/Intsights/flake8-intsights
    rev: v0.1.6
    hooks:
      - id: flake8-intsights
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
