---
exclude: '.*(test|benchmark).*'
repos:
  - repo: https://github.com/Intsights/flake8-intsights
    rev: v0.2.0
    hooks:
      - id: flake8-intsights
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.941
    hooks:
      - id: mypy
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        entry: "yamllint --config-data=\"{extends: default, rules: {line-length: {max: 120}}}\""
